import type { Product } from "@/lib/types";

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "demo-1",
    slug: "specimen-01-ethiopia",
    name: "Specimen_01: Ethiopia",
    description:
      "Gedeo bölgesinden anaerobik natural işlem. Yasemin, bergamot ve limon notalarıyla teknik light kavrum.",
    shortDescription: "Yasemin · Bergamot · Limon",
    originCountry: "Ethiopia",
    originRegion: "Yirgacheffe",
    altitude: "2100 - 2300 MASL",
    process: "Anaerobic Natural",
    varietal: "Heirloom",
    batchId: "KRC-2024-08A",
    roastLevel: "Light / Technical",
    flavorNotes: ["Jasmine", "Bergamot", "Lemon"],
    flavorGeometry: {
      acidity: 0.9,
      sweetness: 0.75,
      body: 0.55,
      floral: 0.85,
      fruit: 0.7,
      clarity: 0.8,
    },
    roastLog: {
      roastTime: "8:42",
      dropTemp: "204°C",
    },
    imageUrl: null,
    gallery: [],
    badge: "New Release",
    basePrice: "420.00",
    currency: "TRY",
    stock: 84,
    isActive: true,
    isFeatured: true,
    categoryId: null,
    variants: [
      {
        id: "v1",
        productId: "demo-1",
        sku: "ETH-250",
        weightLabel: "250g",
        price: "420.00",
        stock: 84,
        isActive: true,
      },
    ],
  },
  {
    id: "demo-2",
    slug: "specimen-02-colombia",
    name: "Specimen_02: Colombia",
    description: "Yüksek rakımlı washed process Gesha. Net asidite ve şeffaf gövde.",
    shortDescription: "Çiçeksi · Şeftali · Kakao",
    originCountry: "Colombia",
    originRegion: "Huila",
    altitude: "1900 MASL",
    process: "Washed",
    varietal: "Gesha",
    batchId: "KRC-2024-11F",
    roastLevel: "Light-Medium",
    flavorNotes: ["Floral", "Peach", "Cocoa"],
    flavorGeometry: {
      acidity: 0.8,
      sweetness: 0.7,
      body: 0.6,
      floral: 0.75,
      fruit: 0.65,
      clarity: 0.85,
    },
    roastLog: null,
    imageUrl: null,
    gallery: [],
    badge: null,
    basePrice: "390.00",
    currency: "TRY",
    stock: 42,
    isActive: true,
    isFeatured: true,
    categoryId: null,
    variants: [
      {
        id: "v2",
        productId: "demo-2",
        sku: "COL-250",
        weightLabel: "250g",
        price: "390.00",
        stock: 42,
        isActive: true,
      },
    ],
  },
  {
    id: "demo-3",
    slug: "specimen-03-brazil",
    name: "Specimen_03: Brazil",
    description: "Pulped natural dengenin damak dostu hali. Espresso ve filtre için stabil profil.",
    shortDescription: "Çikolata · Fındık · Karamel",
    originCountry: "Brazil",
    originRegion: "Minas Gerais",
    altitude: "1200 MASL",
    process: "Pulped Natural",
    varietal: "Yellow Bourbon",
    batchId: "KRC-2024-03C",
    roastLevel: "Medium-Dark",
    flavorNotes: ["Chocolate", "Hazelnut", "Caramel"],
    flavorGeometry: {
      acidity: 0.45,
      sweetness: 0.85,
      body: 0.9,
      floral: 0.3,
      fruit: 0.4,
      clarity: 0.55,
    },
    roastLog: null,
    imageUrl: null,
    gallery: [],
    badge: "Limited Stock",
    basePrice: "340.00",
    currency: "TRY",
    stock: 18,
    isActive: true,
    isFeatured: true,
    categoryId: null,
    variants: [
      {
        id: "v3",
        productId: "demo-3",
        sku: "BRA-250",
        weightLabel: "250g",
        price: "340.00",
        stock: 18,
        isActive: true,
      },
    ],
  },
];

export function resolveProducts(apiProducts: Product[], featuredOnly = false) {
  if (apiProducts.length) {
    if (!featuredOnly) return apiProducts;
    const featured = apiProducts.filter((p) => p.isFeatured);
    return (featured.length ? featured : apiProducts).slice(0, 6);
  }
  return DEMO_PRODUCTS;
}
